import Head from 'next/head'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Next e-commerce</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className='text-3xl font-bold align-middle'>Next e-commerce</h1>
    </div>
  )
}
